replicaCount: 2

image:
  repository: node
  tag: latest
  pullPolicy: IfNotPresent

podAnnotations: {}

extraVolumes: []
extraVolumeMounts: []

initJob: false

env: []
  # - name: VARIABLE
  #   value: value

envFrom: []
  # - secretRef:
  #     name: secret-name

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    # nginx.ingress.kubernetes.io/proxy-body-size: "32m"
  hosts:
    # - name: node.local
    #   path: /
  tls: []
    # - secretName: node-tls
    #   hosts:
    #     - node.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
