{{- if .Values.ingress.enabled -}}

{{- $serviceName := .Release.Name -}}
{{- $servicePort := .Values.service.targetPort -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name | trimSuffix "-" }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name | quote }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
  {{- end}}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
