{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{- printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name | quote }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{- printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
            servicePort: {{ .Values.service.targetPort }}
  {{- end}}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
