apiVersion: v1
kind: Service
metadata:
  name: {{ template "utils.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ template "utils.fullname" . }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
